export const AI_WORDS: readonly string[] = [
  'delve',
  'navigate',
  'navigating',
  'robust',
  'leverage',
  'leveraging',
  'ecosystem',
  'transformative',
  'revolutionary',
  'groundbreaking',
  'comprehensive',
  'holistic',
  'nuanced',
  'facilitate',
  'facilitates',
  'enhance',
  'enhanced',
  'enhances',
  'streamline',
  'streamlined',
  'foster',
  'fostering',
  'empower',
  'empowering',
  'synergy',
  'paradigm',
  'innovative',
  'cutting-edge',
  'state-of-the-art',
  'game-changing',
  'unleash',
  'harness',
  'harnessing',
  'pivotal',
  'crucial',
  'paramount',
  'imperative',
  'multifaceted',
  'interconnected',
  'seamlessly',
  'dynamically',
  'intricately',
  'fundamentally',
  'underscore',
  'elucidate',
  'expound',
  'encompass',
  'encompasses',
  'encompassing',
  'realm',
  'landscape',
  'tapestry',
  'mosaic',
  'spectrum',
  'plethora',
  'myriad',
  'cornucopia',
  'dizzying',
  // Additional AI-typical words
  'democratization',
  'proactive',
  'proactively',
  'embrace',
  'embracing',
  'nurture',
  'nurturing',
  'stewardship',
  'evolving',
  'forward-thinking',
];

export const AI_PHRASES: readonly string[] = [
  'it is worth noting',
  "it's worth noting",
  'it is important to note',
  "it's important to note",
  'it is crucial to note',
  "it's crucial to note",
  'it is essential to note',
  "it's essential to note",
  'in conclusion',
  'in summary',
  'to summarize',
  "in today's world",
  "in today's digital age",
  'in the modern world',
  'in the digital age',
  'in this day and age',
  'in an increasingly',
  'in our increasingly',
  'plays a crucial role',
  'plays a pivotal role',
  'plays an important role',
  'of paramount importance',
  'it goes without saying',
  'needless to say',
  'at the end of the day',
  'when all is said and done',
  'the fact of the matter',
  'in the grand scheme of things',
  'not only but also',
  'delve deeper into',
  'dive deeper into',
  'shed light on',
  'shine a light on',
  'cast light on',
  'pave the way for',
  'paves the way for',
  'bridge the gap',
  'bridge the divide',
  'level the playing field',
  'game changer',
  'holy grail',
  'silver bullet',
  'perfect storm',
  'perfect synergy',
  'seamless integration',
  'seamless experience',
  'unprecedented scale',
  'unprecedented growth',
  'unprecedented challenges',
  'new normal',
  // Additional AI-typical phrases
  'looking ahead',
  'one of the most significant',
  'one of the most important',
  'as we navigate',
  'it is essential that',
];
