export const INTENSIFIERS: readonly string[] = [
  'absolutely',
  'completely',
  'extremely',
  'incredibly',
  'remarkably',
  'tremendously',
  'truly',
  'utterly',
  'exceptionally',
  'extraordinarily',
  'phenomenally',
  'immensely',
  'vastly',
  'hugely',
  'enormously',
  'tremendous',
  'staggering',
  'mind-blowing',
  'breathtaking',
  'unbelievable',
  'unprecedented',
  'unparalleled',
  'unmatched',
  'unsurpassed',
  'incomparable',
  'peerless',
  'ultimate',
  'definitive',
  'quintessential',
  'exemplary',
  'paramount',
  'quintessential',
  'archetypal',
  'quintessentially',
];

export const SUPERLATIVES: readonly string[] = [
  'best',
  'greatest',
  'largest',
  'biggest',
  'highest',
  'most important',
  'most significant',
  'most critical',
  'most crucial',
  'most essential',
  'most remarkable',
  'most impressive',
  'most notable',
  'most extraordinary',
  'most exceptional',
  'most outstanding',
  'most groundbreaking',
  'most revolutionary',
  'most innovative',
  'most transformative',
  'most impactful',
  'most influential',
  'world-class',
  'best-in-class',
  'industry-leading',
  'market-leading',
  'top-tier',
  'first-rate',
  'second-to-none',
  'unbeatable',
  'unrivaled',
];
