export const MARKETING_PHRASES: readonly string[] = [
  'game-changer',
  'game changing',
  'revolutionary',
  'groundbreaking',
  'cutting-edge',
  'bleeding-edge',
  'state-of-the-art',
  'best-of-breed',
  'best in class',
  'world-class',
  'industry-leading',
  'market-leading',
  'next-generation',
  'next generation',
  'paradigm shift',
  'disruptive',
  'transformational',
  'transformative',
  'innovative solutions',
  'innovative approach',
  'value proposition',
  'unique value',
  'competitive advantage',
  'strategic advantage',
  'unmatched capabilities',
  'comprehensive solution',
  'end-to-end solution',
  'turnkey solution',
  'seamless integration',
  'seamless experience',
  'frictionless',
  'effortless',
  'hassle-free',
  'worry-free',
  'risk-free',
  'fail-safe',
  'foolproof',
  'proven track record',
  'battle-tested',
  'enterprise-grade',
  'mission-critical',
  'business-critical',
  'scalable solution',
  'future-proof',
  'future-ready',
  'future-facing',
  'forward-thinking',
  'forward-looking',
  'visionary',
  'pioneering',
  'trailblazing',
  'trend-setting',
  'market-disrupting',
  'category-defining',
  'category-creating',
  'first-mover advantage',
  'early adopter',
  'early mover',
  'impressive features',
  'powerful capabilities',
  'robust platform',
  'flexible architecture',
  'agile methodology',
  'rapid deployment',
  'quick win',
  'low-hanging fruit',
  'easy win',
  'no-brainer',
  'slam dunk',
  'home run',
  'knock it out of the park',
  'level up',
  'supercharge',
  'turbocharge',
  'accelerate growth',
  'drive results',
  'maximize value',
  'optimize performance',
  'unlock potential',
  'unleash power',
  'harness the power',
  'leverage the power',
  'tap into',
  'capitalize on',
  'seize the opportunity',
  "don't miss out",
  'act now',
  'limited time',
  'exclusive offer',
  'special promotion',
];
