export const VAGUE_ATTRIBUTION_PHRASES: readonly string[] = [
  'experts agree',
  'experts say',
  'experts believe',
  'experts suggest',
  'experts warn',
  'experts claim',
  'experts argue',
  'experts contend',
  'experts maintain',
  'experts assert',
  'studies show',
  'studies indicate',
  'studies suggest',
  'studies reveal',
  'studies demonstrate',
  'studies confirm',
  'studies prove',
  'studies find',
  'research shows',
  'research indicates',
  'research suggests',
  'research reveals',
  'research demonstrates',
  'research confirms',
  'research proves',
  'research finds',
  'research indicates',
  'scientists say',
  'scientists believe',
  'scientists suggest',
  'scientists claim',
  'scientists argue',
  'scientists warn',
  'many believe',
  'many argue',
  'many suggest',
  'many think',
  'many say',
  'some believe',
  'some argue',
  'some suggest',
  'some think',
  'some say',
  'critics argue',
  'critics say',
  'critics claim',
  'critics suggest',
  'critics contend',
  'supporters say',
  'supporters argue',
  'supporters claim',
  'analysts say',
  'analysts believe',
  'analysts suggest',
  'observers note',
  'observers say',
  'observers believe',
  'commentators say',
  'commentators argue',
  'pundits say',
  'pundits argue',
  'insiders say',
  'insiders claim',
  'sources say',
  'sources claim',
  'sources indicate',
  'reports suggest',
  'reports indicate',
  'reports say',
  'reports claim',
  'surveys show',
  'surveys indicate',
  'surveys suggest',
  'polls show',
  'polls indicate',
  'polls suggest',
  'data suggests',
  'data indicates',
  'data shows',
  'statistics show',
  'statistics indicate',
  'statistics suggest',
  'evidence suggests',
  'evidence indicates',
  'evidence shows',
  'findings suggest',
  'findings indicate',
  'findings show',
  'it has been suggested',
  'it has been shown',
  'it has been demonstrated',
  'it has been proven',
  'it is widely believed',
  'it is generally agreed',
  'it is commonly accepted',
  'it is often said',
  'it is frequently claimed',
  'it has long been known',
  'it has long been believed',
  'it is believed that',
  'it is thought that',
  'it is said that',
  'it is claimed that',
  'it is argued that',
  'it is suggested that',
  'there is evidence that',
  'there is research that',
  'there are studies that',
  'there are indications that',
  'common knowledge suggests',
  'general consensus is',
  'growing consensus is',
  'emerging consensus is',
  'broad agreement that',
  'widespread agreement that',
];
