export const OVERGENERALIZATION_PHRASES: readonly string[] = [
  'everyone knows',
  'everybody knows',
  'everyone agrees',
  'everybody agrees',
  'everyone believes',
  'everybody believes',
  'everyone understands',
  'everybody understands',
  'everyone recognizes',
  'everybody recognizes',
  'no one doubts',
  'nobody doubts',
  'no one disputes',
  'nobody disputes',
  'no one questions',
  'nobody questions',
  'no one denies',
  'nobody denies',
  'it is well established',
  'it is well known',
  'it is well documented',
  'it is well understood',
  'it is well recognized',
  'it is well accepted',
  'it is universally accepted',
  'it is universally agreed',
  'it is universally recognized',
  'it is universally understood',
  'it is universally acknowledged',
  'it is universally known',
  'universal consensus',
  'broad consensus',
  'general consensus',
  'widespread consensus',
  'common consensus',
  'global consensus',
  'there is no doubt',
  'there is no question',
  'there is no dispute',
  'there is no disagreement',
  'there is no debate',
  'without doubt',
  'without question',
  'without dispute',
  'without disagreement',
  'without debate',
  'undisputed fact',
  'unquestionable fact',
  'undeniable fact',
  'indisputable fact',
  'irrefutable fact',
  'clearly established',
  'clearly demonstrated',
  'clearly proven',
  'clearly shown',
  'clearly evident',
  'obviously true',
  'obviously correct',
  'obviously right',
  'obviously the case',
  'patently obvious',
  'plainly obvious',
  'self-evident',
  'self-evidently',
  'goes without saying',
  'needless to say',
  'it stands to reason',
  'it makes sense that',
  'common sense tells us',
  'common sense suggests',
  'common sense dictates',
  'all experts agree',
  'all studies show',
  'all research indicates',
  'all evidence points to',
  'all signs point to',
  'all indications are',
  'all evidence suggests',
  'all research shows',
  'always has been',
  'always will be',
  'has always been',
  'will always be',
  'throughout history',
  'across all cultures',
  'in all societies',
  'in every culture',
  'in every society',
  'in all contexts',
  'in every context',
  'in all situations',
  'in every situation',
  'in all cases',
  'in every case',
];
