export const SUPERFICIAL_PHRASES: readonly string[] = [
  'it is worth noting',
  "it's worth noting",
  'it is important to note',
  "it's important to note",
  'it is crucial to note',
  "it's crucial to note",
  'it is essential to note',
  "it's essential to note",
  'it is interesting to note',
  "it's interesting to note",
  'worth noting',
  'important to note',
  'crucial to note',
  'essential to note',
  'interesting to note',
  'significant developments',
  'significant changes',
  'significant progress',
  'significant improvements',
  'significant impact',
  'significant implications',
  'substantial developments',
  'substantial changes',
  'substantial progress',
  'substantial improvements',
  'substantial impact',
  'notable developments',
  'notable changes',
  'notable progress',
  'notable improvements',
  'notable impact',
  'considerable developments',
  'considerable changes',
  'considerable progress',
  'considerable improvements',
  'considerable impact',
  'one could argue',
  'one might argue',
  'one could suggest',
  'one might suggest',
  'one could say',
  'one might say',
  'one could claim',
  'one might claim',
  'it could be argued',
  'it might be argued',
  'it could be suggested',
  'it might be suggested',
  'it could be said',
  'it might be said',
  'it could be claimed',
  'it might be claimed',
  'it can be argued',
  'it may be argued',
  'it can be suggested',
  'it may be suggested',
  'it can be said',
  'it may be said',
  'it can be claimed',
  'it may be claimed',
  'various sources indicate',
  'various sources suggest',
  'various sources claim',
  'various studies show',
  'various studies indicate',
  'various studies suggest',
  'multiple sources indicate',
  'multiple sources suggest',
  'multiple sources claim',
  'multiple studies show',
  'multiple studies indicate',
  'multiple studies suggest',
  'numerous sources indicate',
  'numerous sources suggest',
  'numerous sources claim',
  'numerous studies show',
  'numerous studies indicate',
  'numerous studies suggest',
  'several sources indicate',
  'several sources suggest',
  'several sources claim',
  'several studies show',
  'several studies indicate',
  'several studies suggest',
  'a number of sources',
  'a number of studies',
  'a range of sources',
  'a range of studies',
  'a variety of sources',
  'a variety of studies',
  'some evidence suggests',
  'some evidence indicates',
  'some evidence shows',
  'some research suggests',
  'some research indicates',
  'some research shows',
  'certain sources',
  'certain studies',
  'certain experts',
  'certain researchers',
  'certain analysts',
  'various factors',
  'multiple factors',
  'numerous factors',
  'several factors',
  'various reasons',
  'multiple reasons',
  'numerous reasons',
  'several reasons',
  'various aspects',
  'multiple aspects',
  'numerous aspects',
  'several aspects',
  'broad range of',
  'wide range of',
  'wide variety of',
  'diverse range of',
  'extensive range of',
];
